jdk:
  - openjdk17
before_install:
  - sdk install java 17.0.9-open || true
  - sdk use java 17.0.9-open
install:
  - ./gradlew :openvins-lib:assembleRelease :openvins-lib:publishReleasePublicationToMavenLocal
